#!/bin/bash

# Run with ./gen-Dockerfile.sh > Dockerfile
VERSION=1.22.0
echo "# Generated by $0 from https://github.com/nginxinc/docker-nginx/tree/$VERSION"
curl -Ls https://raw.githubusercontent.com/nginxinc/docker-nginx/${VERSION}/modules/Dockerfile.alpine | sed 's/mainline-/stable-/' | sed 's/^ARG ENABLED_MODULES.*/ARG ENABLED_MODULES="'"$(cat modules.lst | xargs echo)"'"/'

cat <<EOF
LABEL maintainer "Feng Zhou <feng.zh@gmail.com>"
RUN apk add --update tar && rm -rf /var/lib/apt/lists/* /var/cache/apk/*
COPY entrypoint/*.sh /docker-entrypoint.d/
ENV NGINX_WATCH_INTERVAL=10s NGINX_LOG_LEVEL=warn NGINX_CONFIG_MODE=legacy
# Default enable modules
ENV NGINX_LOAD_MODULES="ngx_http_auth_ldap_module ngx_http_headers_more_filter_module"
EOF
